# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: Test
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
      architecture: x64
  - script: pip3 install .
    displayName: Run pip
  - script: pylint physlr
    displayName: Run pylint
  - script: make -C indexlr
    displayName: Build physlr-indexlr
  - script: make -C indexlr check
    displayName: Test physlr-indexlr
