# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: Test
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
      architecture: x64
  - script: pip3 install pylint .
    displayName: Install Python packages
  - script: pylint physlr
    displayName: Run pylint
  - script: make -C src all
    displayName: Compile C++ source code
  - script: make -C src check
    displayName: Test C++ programs
